version: '3.4'

services:
  server:
    build: ./
    ports:
     - '8080:8080'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:  todo
    ports:
       - '5432:5432'
